#!/usr/bin/env python3
"""Regenerate the llm-d endpoints ConfigMap from the live engine pod.

The EPP's file-discovery plugin does not resolve hostnames -- every entry must
carry a literal IPv4 address (guides/no-kubernetes-deployment/README.md). Our
four vLLM servers live inside one pod (neutral-0, DP_SIZE_LOCAL=4) on ports
8000..8003, so all four entries share an address and differ only by port, and
that address changes every time the engine is restarted. Every condition
restarts the engine, so this runs once per condition, before load starts.

The EPP watches the file with watchFile: true and reloads on an atomic rewrite,
so no EPP restart is needed for an address change. A kubelet ConfigMap update
is not atomic from the container's point of view in the way `mv` is, but it does
replace the symlinked directory in one step, which is the same signal.

Verification is the point of this script, not convenience: it reads back what
the ConfigMap now contains and compares it against what was asked for, because
a stale endpoints file sends every request to an address that no longer exists
and the failure looks like an engine problem rather than a configuration one.

Usage:
    python3 ms_dev/scripts/llmd_endpoints.py                 # apply + verify
    python3 ms_dev/scripts/llmd_endpoints.py --print         # print, do not apply
"""

import argparse
import json
import subprocess
import sys

ENGINE_NS = "llumnix"
ENGINE_POD = "neutral-0"
# Which ports the fleet actually listens on. Like MODEL_LABEL below, this used
# to be a literal, which made it another place a fleet-shape change had to be
# remembered -- and the failure is silent: llm-d would register four endpoints
# for an eight-instance fleet, route to half of it, and report that as a result.
def _engine_ports(default=(8000, 8001, 8002, 8003)):
    try:
        out = subprocess.run(
            ["kubectl", "-n", "llumnix", "get", "cm", "llumnix-model",
             "-o", "jsonpath={.data.ENGINE_PORTS}"],
            capture_output=True, text=True, timeout=20)
        v = out.stdout.strip()
        return tuple(int(x) for x in v.split(",") if x.strip()) if v else default
    except Exception:
        return default


ENGINE_PORTS = _engine_ports()
LLMD_NS = "llmd"
CONFIGMAP = "llmd-endpoints"
# The label llm-d routes on has to name the model the engines actually serve.
# It used to be a literal here, which made it the eighth place a model switch had
# to be remembered, and the failure is silent in the worst way: llm-d would route
# to endpoints labelled with a model none of them serve. It now comes from the
# same ConfigMap the runner templates read, written by
# ms_dev/scripts/switch_model.py, with the historical value as the fallback for
# a cluster where that ConfigMap does not exist yet.
def _model_label(default="meta-llama/Meta-Llama-3.1-70B-Instruct"):
    import subprocess
    try:
        out = subprocess.run(
            ["kubectl", "-n", "llumnix", "get", "cm", "llumnix-model",
             "-o", "jsonpath={.data.MODEL_ID}"],
            capture_output=True, text=True, timeout=20)
        v = out.stdout.strip()
        return v or default
    except Exception:
        return default


MODEL_LABEL = _model_label()


def kubectl(args, check=True):
    r = subprocess.run(["kubectl", *args], capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.exit(f"kubectl {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout


def engine_ip() -> str:
    ip = kubectl(["-n", ENGINE_NS, "get", "pod", ENGINE_POD,
                  "-o", "jsonpath={.status.podIP}"]).strip()
    if not ip:
        sys.exit(f"{ENGINE_POD} has no pod IP yet")
    return ip


def endpoints_yaml(ip: str) -> str:
    lines = [
        "# Generated by ms_dev/scripts/llmd_endpoints.py -- do not edit by hand.",
        "# One entry per vLLM server inside neutral-0; the address is the pod IP",
        "# and changes on every engine restart.",
        "endpoints:",
    ]
    for i, port in enumerate(ENGINE_PORTS):
        lines += [
            f"  - name: vllm-{i}",
            f"    address: {ip}",
            f'    port: "{port}"',
            "    labels:",
            f"      model: {MODEL_LABEL}",
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", dest="print_only", action="store_true",
                    help="print the endpoints file and exit without applying")
    a = ap.parse_args()

    ip = engine_ip()
    body = endpoints_yaml(ip)

    if a.print_only:
        print(body, end="")
        return 0

    manifest = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": CONFIGMAP,
            "namespace": LLMD_NS,
            "labels": {"app.kubernetes.io/part-of": "llmd-baseline"},
        },
        "data": {"endpoints.yaml": body},
    }
    r = subprocess.run(["kubectl", "apply", "-f", "-"], input=json.dumps(manifest),
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"apply failed: {r.stderr.strip()}")
    print(r.stdout.strip())

    # Read back and compare. A silent mismatch here is the failure this script
    # exists to prevent.
    got = kubectl(["-n", LLMD_NS, "get", "cm", CONFIGMAP,
                   "-o", "jsonpath={.data.endpoints\\.yaml}"])
    if got != body:
        sys.exit("ABORT: ConfigMap content does not match what was written")
    n = got.count("address: ")
    if n != len(ENGINE_PORTS):
        sys.exit(f"ABORT: wrote {n} endpoints, wanted {len(ENGINE_PORTS)}")
    print(f"verified: {CONFIGMAP} has {n} endpoints at {ip}:"
          f"{','.join(str(p) for p in ENGINE_PORTS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
